name: guia_moteis_desafio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  http: ^1.3.0
  dartz: ^0.10.1
  mocktail: ^1.0.4
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
